HOUSING_LABELS = {"EVIDENCE_OF_HOUSING", "TEMPORARY_HOUSING"}
HOMELESS_OUTCOME_LABELS = {"EVIDENCE_OF_HOMELESSNESS",}
UNSTABLE_OUTCOME_LABELS = {"TEMPORARY_HOUSING", "DOUBLING_UP",
                           "RISK_OF_HOMELESSNESS"
                           }

# Binary classification
BIN_UNSTABLE_OUTCOME_LABELS = HOMELESS_OUTCOME_LABELS.union(UNSTABLE_OUTCOME_LABELS)

# Main concepts of interest
PRIMARY_LABELS = HOUSING_LABELS.union(BIN_UNSTABLE_OUTCOME_LABELS)