HOUSING_LABELS = {"EVIDENCE_OF_HOUSING", "TEMPORARY_HOUSING"}
HOMELESS_OUTCOME_LABELS = {"EVIDENCE_OF_HOMELESSNESS",}
UNSTABLE_OUTCOME_LABELS = {"TEMPORARY_HOUSING", "DOUBLING_UP", "RISK_OF_HOMELESSNESS"}

# Binary classification
BIN_UNSTABLE_OUTCOME_LABELS = {"TEMPORARY_HOUSING", "DOUBLING_UP", "EVIDENCE_OF_HOMELESSNESS"}

# Main concepts of interest
PRIMARY_LABELS = {"DOUBLING_UP", "EVIDENCE_OF_HOMELESSNESS", "EVIDENCE_OF_HOUSING",
         "RISK_OF_HOMELESSNESS", "TEMPORARY_HOUSING"}